### ISSUE TITLE
Use input=date

### ISSUE THREAD

**Issue by kaihendry** [DFE-Digital/govuk-formbuilder#302]
I found this project via https://gds.blog.gov.uk/2021/07/06/making-all-forms-on-gov-uk-accessible-easy-to-use-and-quick-to-process/ and https://govuk-form-builder.netlify.app/form-elements/date-field/ concerned me since it's quite a needlessly complex implementation to collect date especially when https://caniuse.com/input-datetime is very well supported.

**Comment by peteryates** [comment]
Hi Kai. Thanks for getting in touch. This repository is just a library that implements the form functionality outlined in the [GOV.UK Design System](https://design-system.service.gov.uk/components/date-input/) in Ruby on Rails, the actual design work is dicussed and carried out in the [design system](https://github.com/alphagov/govuk-design-system), [backlog](https://github.com/alphagov/govuk-design-system-backlog) and [frontend](https://github.com/alphagov/govuk-frontend) repos.

There is a [date picker component currently in the backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/17), and many services have implemented their own, but the HTML5 date pickers fall short on the accessibility front in many ways, especially on desktop.

* https://www.hassellinclusion.com/blog/input-type-date-ready-for-use/
* https://www.webaxe.org/accessible-date-pickers/

If you're building a service and your user research finds that the built-in picker is suitable and works for your users, by all means go for it. The design system is very much a starting off point rather than a set of absolutes.

**Comment by peteryates** [comment]
Going to close this as I think it's been answered and there's enough info above to find the relevant info from upstream sources.
