### ISSUE TITLE
It's not possible to make radio labels a regular font weight when a hint is provided

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/govuk-formbuilder#315]
In the following example it's not possible to change the font weight of these labels from bold to regular.

Setting `bold_labels: false` in the options seems to have no effect because of https://github.com/DFE-Digital/govuk-formbuilder/blob/40e319c01553e7eed69d4bd28c49aed665ffad20/lib/govuk_design_system_formbuilder/elements/radios/collection.rb#L24

![localhost_3000_registration_funding-your-npq](https://user-images.githubusercontent.com/319055/132711813-90a25c0b-fcee-49c1-9c99-f7f05ac1fddd.png)

How that call is being made:

```<%= f.govuk_collection_radio_buttons :funding,
        @form.options,
        :value,
        :text,
        :description,
        bold_labels: false,
        legend: { text: "How is your #{@form.course.name} being paid for?" } %>```

**Comment by peteryates** [comment]
This was introduced [_really early_ in the library's development](https://github.com/DFE-Digital/govuk-formbuilder/pull/31/files#diff-8561c32246aa6220332c3afdfdd3e9de2bd97e2c757f1c3a9b31a2465f6279ebR225) and the reason I did it was because having regular text alongside hints made them kind of blend into each other.

It could clearly work better though. My gut reaction would be to set `bold_labels: nil` as a default and then bolden them depending on whether or not there are hints (continuing the current behaviour), but if `bold_labels:` is set either `true` or `false` to respect the decision.

I'll have a look today.
